name: 1.0.$(BuildID)-${{ parameters.service }}-${{ parameters.resource }}

trigger: none

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: useCustomEnvironments
    displayName: "Use Custom Environments"
    type: boolean
    default: false
  - name: service
    displayName: Select service that needs to be deployed
    type: string
    values:
      - fcp-data-access-layer-api
      - fcp-find-ai-frontend
      - ffc-demo-web
      - ffc-demo-payment-web
      - ffc-ffd-frontend-poc
      - ffc-sfd-landing-page
      - ffc-sfd-messages
      - ffc-sfd-messages-processor
      - ffc-sfd-permissions
    default: ffc-demo-web
  - name: resource
    displayName: Resource Type to deploy
    type: string
    values:
      - application-domain
    default: application-domain

extends:
  template: /.azuredevops/templates/generic-template.yaml
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    useCustomEnvironments: ${{ parameters.useCustomEnvironments }}
    program: ffc
    service: ${{ parameters.service }}
    resource: ${{ parameters.resource }}

