name: 1.0.$(BuildID)-${{ parameters.service }}-${{ parameters.resource }}

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - infra/services/ffc/*
  drafts: false

trigger: none

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: service
    displayName: Select service that needs to be deployed
    type: string
    values:
      - ffc-sfd
      - fcp-data-access-layer-api
      - fcp-find-ai-frontend
      - ffc-demo-web
      - ffc-demo-payment-web
      - ffc-ffd-frontend-poc
      - ffc-sfd-ahwp-stub
      - ffc-sfd-permissions
      - ea-wq-incident-web
    default: ffc-demo-web

  - name: ingressType
    displayName: Select ingress type of the service
    type: string
    values:
      - internal
      - external
    default: internal
    
  - name: resource
    displayName: Resource Type to deploy
    type: string
    values:
      - application-domain
    default: application-domain
  - name: includePlatformEnvs
    displayName: Include Platform Environments
    type: boolean
    default: false

extends:
  template: /.azuredevops/templates/generic-template.yaml
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    useCustomEnvironments: false
    includePlatformEnvs: ${{ parameters.includePlatformEnvs }}
    program: ffc
    service: ${{ parameters.service }}
    ingressType: ${{ parameters.ingressType }}
    resource: ${{ parameters.resource }}
